### ISSUE TITLE
Dart 2 Support?

### ISSUE THREAD

**Issue by kjordan2001** [jnguillerme/mqtt.dart#13]
I'm trying to add this to a flutter app which has Dart 2 installed, but it seems like this is still written for Dart 1 since I'm getting: 

> Because every version of flutter_test from sdk depends on args 1.4.3 and mqtt >=1.1.0 depends on args ^0.12.0+2, flutter_test from sdk is incompatible with mqtt >=1.1.0.
So, because griller depends on both mqtt ^1.1.0 and flutter_test any from sdk, version solving failed.

**Comment by jnguillerme** [comment]
You are correct. I need to migrate the package to dart 2.
I will work on that this week.

**Comment by jnguillerme** [comment]
The package has been updated. Any issue, let me know.

**Comment by LuLeRoemer** [comment]
Maybe I'm not using it correctly, but unfortunately I get the folowing error when using Dart 2 in Flutter:
```
I/flutter (14838): The following assertion was thrown building NotificationListener<KeepAliveNotification>:
I/flutter (14838): type 'Future<dynamic>' is not a subtype of type 'Future<int>'
I/flutter (14838): 
I/flutter (14838): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (14838): more information in this error message to help you determine and fix the underlying cause.
I/flutter (14838): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (14838):   https://github.com/flutter/flutter/issues/new
I/flutter (14838): 
I/flutter (14838): When the exception was thrown, this was the stack:
I/flutter (14838): #0      MqttClient.connect (file:///opt/flutter/.pub-cache/hosted/pub.dartlang.org/mqtt-1.1.2/lib/mqtt_client.dart:55:22)
I/flutter (14838): #1      _SensorListState.setMQTT2 (file:///home/lukas/develop/softwareprojekt_a/pflanzen2/pflanzen2_app/lib/main.dart:196:11)
I/flutter (14838): #2      _SensorListState.initState (file:///home/lukas/develop/softwareprojekt_a/pflanzen2/pflanzen2_app/lib/main.dart:188:9)
I/flutter (14838): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3764:58)
```

The error does not occure using Dart 1 (--no-preview-dart-2 flag in Flutter).
Thanks in advance for your support!

**Comment by jnguillerme** [comment]
Hi,
This issue should be fixed now. I will release a new package shortly. 
I'll let you know once done ( I have to include a few other fixes).

Best regards,

**Comment by jnguillerme** [comment]
Please try with package 1.1.3. It should fix the issue.
