### ISSUE TITLE
Connection Refused: bad user name or password

### ISSUE THREAD

**Issue by arden** [jnguillerme/mqtt.dart#14]
when i'm use username and password to connect mqtt server, there is some errors, but i'm sure the username and password is correct.

and the mqtt.dart version is the last version: 1.1.2 and Flutter 0.4.4, mqtt server use the Aedes.

```
    this.c = new MqttClient(new MqttConnectionIOSocket.setOptions(host: host, port: port),
        clientID: this.clientId,
        qos: QOS_1,
        cleanSession: true,
        userName: "sayone",
        password: "sayone2018"
```
and i'm print the username and password on the mqtt server program:
`2018-06-07T19:18:35+0800 <debug> app.js:88 (Aedes.self.aedes.authenticate) username: sayone2018, password: undefined`
the password become to username, and password become to undefined.

[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
type 'Future<dynamic>' is not a subtype of type 'Future<int>'
#0      MqttClient.connect (file:///Users/weibo/data/soft/flutter/.pub-cache/hosted/pub.dartlang.org/mqtt-1.1.2/lib/mqtt_client.dart:55:22)
#1      MyMqttClient.listen (package:saytoken_flutter/mqtt/MyMqttClient.dart:35:12)
<asynchronous suspension>
#2      _LoginPageState.login (package:saytoken_flutter/redux/presentation/LoginPage.dart:27:22)
<asynchronous suspension>
#3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
#4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
#7      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
#8      GestureArenaManager.sweep (package:flutter/src/gestures/aren<…>
flutter: Opening session
flutter: Connection Refused: bad user name or password
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
Connection Refused: bad user name or password
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1114:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
flutter: Connection to broker lost
flutter: Connection lost

**Comment by rahulmranjith** [comment]
any update on this ?I am also getting the same problem when using user name password

**Comment by jnguillerme** [comment]
Hi,
Sorry for the delay.
I managed to reproduce your issue. I will work on a fix and let you know once ready.

best regards

**Comment by jnguillerme** [comment]
Please try with package 1.1.3. It should fix the issue.

**Comment by Smartauto** [comment]
Hi
Was this issue Fixed, I am Getting Same Issue.

Also I have to Downgrade Dart SDK Version to run this. 
Do you plan to Upgrade this to dartsdk 2.0+
