### ISSUE TITLE
compiler message: Try changing the type of the left hand side, or casting the right hand side to 'dart.core::String'.

### ISSUE THREAD

**Issue by sonalirawat** [jnguillerme/mqtt.dart#15]
file:///home/nagesh/fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/mqtt-1.1.2/lib/mqtt_options.dart:5:40: Error: A value of type 'dart.core::List<dart.core::String>' can't be assigned to a variable of type 'dart.core::String'.
compiler message: Try changing the type of the left hand side, or casting the right hand side to 'dart.core::String'.
compiler message:                         'mqtt_broker' :['host','port', 'user', 'password'],
compiler message:                                        ^

**Comment by jnguillerme** [comment]
It should be fixed with package 1.1.3.
Let me know if that's not the case.
