### ISSUE TITLE
dart:io not Available on Dartium

### ISSUE THREAD

**Issue by rosaldanha** [jnguillerme/mqtt.dart#2]
Hello,
    I´m trying to use the html websocket, as showed in the sample, but when I run, I got the following error:

```
The Request buit-in library is not available on Dartium. 'package:mqtt/mqtt_shared.dart': error: line 6 pos 1: library handler failed
 import 'dart:io':
```

^: package:mqtt/mqtt_shared.dart

   To my understanding the dart:io cant be used in web apps, is this correct ? 

   Thanks in advance !

**Comment by jnguillerme** [comment]
Hi,
I haven’t worked on that library for quite some time, so it got developed with an old version on DART. I guess this is the reason for your error.
I will work on supporting the latest DART version.

I’ll keep you posted.

thank you,

Jean-Noel
