### ISSUE TITLE
Websocket seems to not work

### ISSUE THREAD

**Issue by banalg** [jnguillerme/mqtt.dart#3]
Hello,

I tried the mqtt_pub.dart test program with two MQTT brokers and the programm seems to block after `Opening session`.

`PS C:\Users\[...]\mqtt\mqtt.dart\example\mqtt_pub> dart mqtt_pub.dart -U ws://test.mosquitto.org:8080/ -t hello -m bob`
`starting`
`[WebSocket] Connecting to ws://test.mosquitto.org:8080/`
`Opening session`
`>>> Type(1) Len(41) QoS(0) DUP(0) retain(0) <163906778173115100112360300001010410110810811199108111991070111191051081081129712110811197100>]`

**Comment by banalg** [comment]
I forked the library and now mqtt-websockets works with http://test.mosquitto.org. It was because of the lack of the sec-protocole header in the HTTP Upgrade request.

I'll a pull request un few days

**Comment by jnguillerme** [comment]
Thanks for raising and fixing the issue.
