### ISSUE TITLE
Invalid value in MqttMessagePublish.decodeVariableHeader

### ISSUE THREAD

**Issue by gottfriedsz** [jnguillerme/mqtt.dart#5]
Hi

I am getting an error during decode of a simple message which is correct (multiple clients in java & javascript that can handle it), but the dart seems to have a problem. I have added an additional log to see the context and data of the message.

Observatory listening on http://127.0.0.1:60887/
Opening session
\>\>\> Type(1) Len(26) QoS(0) DUP(0) retain(0) <162406778173115100112320300101009711411699108105101110116>]
\<\<\< Type(2) Len(4) QoS(0) DUP(0) retain(0) <>]
Connection Accepted
Subscribe to sensor/temperatures/all - QoS: 0 - Message ID: 1
\>\>\> Type(8) Len(30) QoS(0) DUP(0) retain(0) <1282801023115101110115111114471161011091121011149711611711410111547971081080>]
[Suback] Granted QOS level: 0
\<\<\< Type(9) Len(5) QoS(0) DUP(0) retain(0) <>]
Subscription done - ID: 1 - Qos: 0
**ERROR: data([1, 0, 23, 115, 101, 110, 115, 111, 114, 47, 116, 101, 109, 112, 101, 114, 97, 116, 117, 114, 101, 115, 47, 97, 108, 108, 123, 34, 116, 105, 109, 101, 34, 32, 58, 32, 34, 50, 48, 49, 54, 45, 49, 50, 45, 50, 56, 32, 49, 50, 58, 53, 56, 58, 49, 55, 34, 44, 32, 34, 109, 111, 100, 101, 108, 34, 32, 58, 32, 34, 65, 109, 98, 105, 101, 110, 116, 32, 87, 101, 97, 116, 104, 101, 114, 32, 70, 48, 48, 55, 84, 72, 32, 84, 104, 101, 114, 109, 111, 45, 72, 121, 103, 114, 111, 109, 101, 116, 101, 114, 34, 44, 32, 34, 100, 101, 118, 105, 99, 101, 34, 32, 58, 32, 49, 54, 49, 44, 32, 34, 99, 104, 97, 110, 110, 101, 108, 34, 32, 58, 32, 56, 44, 32, 34, 98, 97, 116, 116, 101, 114, 121, 34, 32, 58, 32, 34, 79, 107, 34, 44, 32, 34, 116, 101, 109, 112, 101, 114, 97, 116, 117, 114, 101, 95, 67, 34, 32, 58, 32, 50, 49, 46, 55, 55, 56, 44, 32, 34, 104, 117, 109, 105, 100, 105, 116, 121, 34, 32, 58, 32, 53, 51, 125]) data.length(204 topicLength(256) pos(2)**
Unhandled exception:
RangeError (end): Invalid value: Not in range 2..204, inclusive: 258
#0      RangeError.checkValidRange (dart:core/errors.dart:321)
#1      _TypedListBase.sublist (dart:typed_data:620)
#2      MqttMessagePublish.decodeVariableHeader (package:mqtt/mqtt_message_publish.dart:93:31)
#3      MqttMessage.MqttMessage.decode (package:mqtt/mqtt_message.dart:45:17)
#4      MqttMessagePublish.MqttMessagePublish.decode (package:mqtt/mqtt_message_publish.dart:29:140)
#5      MqttClient._handlePublish (package:mqtt/mqtt_client.dart:302:34)
#6      MqttClient._processMqttMessage (package:mqtt/mqtt_client.dart:204:30)
#7      MqttClient._processData (package:mqtt/mqtt_client.dart:183:16)
#8      MqttConnectionIOSocket.startListening.<anonymous closure> (package:mqtt/mqtt_connection_io_socket.dart:32:29)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#12     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#13     _StreamController._add (dart:async/stream_controller.dart:635)
#14     _StreamController.add (dart:async/stream_controller.dart:581)
#15     _Socket._onData (dart:io-patch/socket_patch.dart:1680)
#16     _RootZone.runUnaryGuarded (dart:async/zone.dart:1338)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#19     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#20     _StreamController._add (dart:async/stream_controller.dart:635)
#21     _StreamController.add (dart:async/stream_controller.dart:581)
#22     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1247)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:781)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)

Process finished with exit code 255
`

**Comment by szing** [comment]
Its the one that comes with raspian

`mosquitto version 1.3.4 (build date 2014-08-22 06:10:51+0000) starting`

Is it maybe related to the QOS, because I am using QOS = 1

**Comment by LuLeRoemer** [comment]
I'm having the exact same problem. Is there already a solution for the error @jnguillerme ?
I think it's related to the message length. I was able to receive the following message
```json
[{"boxID": 1, "name": "sepp", "sadf": "asdfasdfqqqqq", "address": 12}]
```
but not this one
```json
[{"boxID": 1, "name": "sepp", "sadf": "asdfasdfqqqqqq", "address": 12}]
```
