### ISSUE TITLE
MqttOptions seems not working

### ISSUE THREAD

**Issue by yolkhovyy** [jnguillerme/mqtt.dart#8]
Config.readFileSync() method not found:

Unhandled exception:
NoSuchMethodError: No static method 'readFileSync' declared in class 'Config'.
Receiver: Type: class 'Config'
Tried calling: readFileSync(Instance of '_File')
#0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:196)
#1      MqttOptions.MqttOptions.initFromConfig (package:mqtt/mqtt_options.dart:30:22)
...

**Comment by jnguillerme** [comment]
I've corrected the problem in the latest version of mqtt_options.dart. 
Let me know if any further issue.
I'm also planning to support initialisation from JSON file in a future version.

**Comment by yolkhovyy** [comment]
Ok, thanks - will look at that.

**Comment by jnguillerme** [comment]
It's been released with package 1.1.3.
