### ISSUE TITLE
Not possible to subscribe multiple callbacks in MqttClient.subscribe 

### ISSUE THREAD

**Issue by yolkhovyy** [jnguillerme/mqtt.dart#9]
If I do:

    mqttClient.subscribe(options.topicCmdReqData, options.qosCmd, reqData, 1);
    mqttClient.subscribe(options.topicCmdSetConfig, options.qosCmd, setConfig, 2);

then the setConfig will be called for both topics, the reqData will not be called.

**Comment by jnguillerme** [comment]
Thank you for reporting the problem. It should now be fixed.
Let me know if any further issue.

Cheers.

**Comment by yolkhovyy** [comment]
Thanks for your effort. It seems that authorization (userName/password) stopped working - getting "Connection Refused: not authorized".

**Comment by jnguillerme** [comment]
It's fixed in the latest package (1.1.3)
